Update install script

diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,11 +1,20 @@
 #!/usr/bin/env bash
 set -Ceu
 
+TOOLS=(
+	"npm"
+	"make"
+	"curl"
+)
+
 # Prerequites checking
-if [ -e $(type curl &> /dev/null) ] ; then
-  echo "Curl required to be installed."
-  exit 1
-fi
+for cmd in "${TOOLS[@]}"; do
+  if ! type $cmd &> /dev/null; then
+    echo "$cmd is required to be installed."
+    exit 1
+  fi
+done
+
 
 # Install dotfiles
 ln -snvf "$(pwd)/_vimrc" "$HOME/_vimrc"
@@ -19,8 +28,7 @@ ln -svnf "$(pwd)/etc/_pryrc" "$HOME/.pryrc"
 
 # Install _vimrc
 if [ ! -e "$HOME/.vim" ] ; then
-  curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
-    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
+  curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
   (set -x; vim +PlugInstall +qall)
 fi
 
